config/routes.rb
Esteem::Application.routes.draw do
  resources :suggestion_votes

  resources :radials

  resources :question_responses

  resources :questions

  resources :suggestions

  resources :projects do
    member do
      get 'radials'
      post 'answer_questions'
    end
  end

  resources :organizations
  
  match 'help/radials' => 'help#radials', :as => 'radials_help', :via => :get

  
  devise_for :user

  root :to => 'main#index'

end

app/models/suggestion_vote.rb
class SuggestionVote < ActiveRecord::Base
  belongs_to :suggestion
  belongs_to :user
end

app/controllers/suggestion_votes_controller.rb
class SuggestionVotesController < ApplicationController
  # GET /suggestion_votes
  # GET /suggestion_votes.json
  def index
    @suggestion_votes = SuggestionVote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @suggestion_votes }
    end
  end

  # GET /suggestion_votes/1
  # GET /suggestion_votes/1.json
  def show
    @suggestion_vote = SuggestionVote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @suggestion_vote }
    end
  end

  # GET /suggestion_votes/new
  # GET /suggestion_votes/new.json
  def new
    @suggestion_vote = SuggestionVote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @suggestion_vote }
    end
  end

  # GET /suggestion_votes/1/edit
  def edit
    @suggestion_vote = SuggestionVote.find(params[:id])
  end

  # POST /suggestion_votes
  # POST /suggestion_votes.json
  def create
    @suggestion_vote = SuggestionVote.new(params[:suggestion_vote])

    respond_to do |format|
      if @suggestion_vote.save
        format.html { redirect_to @suggestion_vote.suggestion.project, notice: 'Suggestion vote was successfully created.' }
        format.json { render json: @suggestion_vote, status: :created, location: @suggestion_vote.suggestion.project }
      else
        format.html { render action: "new" }
        format.json { render json: @suggestion_vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /suggestion_votes/1
  # PUT /suggestion_votes/1.json
  def update
    @suggestion_vote = SuggestionVote.find(params[:id])

    respond_to do |format|
      if @suggestion_vote.update_attributes(params[:suggestion_vote])
        format.html { redirect_to @suggestion_vote, notice: 'Suggestion vote was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @suggestion_vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suggestion_votes/1
  # DELETE /suggestion_votes/1.json
  def destroy
    @suggestion_vote = SuggestionVote.find(params[:id])
    @suggestion_vote.destroy

    respond_to do |format|
      format.html { redirect_to suggestion_votes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/suggestion_votes_helper.rb
module SuggestionVotesHelper
end

app/views/suggestion_votes/_form.html.haml
= form_for @suggestion_vote do |f|
  -if @suggestion_vote.errors.any?
    #error_explanation
      %h2= "#{pluralize(@suggestion_vote.errors.count, "error")} prohibited this suggestion_vote from being saved:"
      %ul
        - @suggestion_vote.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :suggestion_id
    = f.number_field :suggestion_id
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :vote
    = f.number_field :vote
  .actions
    = f.submit 'Save'

app/views/suggestion_votes/edit.html.haml
%h1 Editing suggestion_vote

= render 'form'

= link_to 'Show', @suggestion_vote
\|
= link_to 'Back', suggestion_votes_path

app/views/suggestion_votes/index.html.haml
%h1 Listing suggestion_votes

%table
  %tr
    %th Suggestion
    %th Vote
    %th
    %th
    %th

  - @suggestion_votes.each do |suggestion_vote|
    %tr
      %td= link_to suggestion_vote.suggestion.title, suggestion_vote.suggestion
      %td= suggestion_vote.vote
      %td= link_to 'Show', suggestion_vote
      %td= link_to 'Edit', edit_suggestion_vote_path(suggestion_vote)
      %td= link_to 'Destroy', suggestion_vote, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Suggestion vote', new_suggestion_vote_path

app/views/suggestion_votes/new.html.haml
%h1 New suggestion_vote

= render 'form'

= link_to 'Back', suggestion_votes_path

app/views/suggestion_votes/show.html.haml
%p#notice= notice

%p
  %b Suggestion:
  = @suggestion_vote.suggestion_id
%p
  %b User:
  = @suggestion_vote.user_id
%p
  %b Vote:
  = @suggestion_vote.vote

= link_to 'Edit', edit_suggestion_vote_path(@suggestion_vote)
\|
= link_to 'Back', suggestion_votes_path