config/routes.rb
Esteem::Application.routes.draw do
  resources :suggestion_votes

  resources :radials

  resources :question_responses

  resources :questions

  resources :suggestions

  resources :projects do
    member do
      get 'radials'
      post 'answer_questions'
    end
  end

  resources :organizations
  
  match 'help/radials' => 'help#radials', :as => 'radials_help', :via => :get

  
  devise_for :user

  root :to => 'main#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :organization
  
  has_many :radials
  has_many :questions
  has_many :suggestions
  
  
  # Get an array of the questions that this user has not recently answered for
  # this project.
  def get_unanswered_questions_for_user(user)
    raise 'user is nil' if user.nil?
    
    # Get questions the user has answered.
    user_answered_questions = QuestionResponse.where(:user_id => user.id).map(&:question)
    
    # Subtract those from the full set of questions to get the set of any that
    # have not been answered.
    questions - user_answered_questions
  end
  
  def suggestions_ordered_by_vote_score
    suggestions.sort_by { |s| s.vote_score }.reverse
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  
  def _set_project_breadcrumb
    add_breadcrumb @project.name, project_path(@project)
  end
  
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    
    @radials = @project.radials
    @radial_score_map = @radials.map { |r| [r.name, r.score] }
    
    @questions = @project.get_unanswered_questions_for_user(current_user)
    
    @suggestions = @project.suggestions_ordered_by_vote_score.in_groups_of(8, false).first || []
    
    # New Suggestion for form
    @suggestion = Suggestion.new(:project_id => @project.id, :user_id => current_user.id)
    
    # Set breadcrumbs
    _set_project_breadcrumb

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    if (organization_id = params[:organization_id])
      @project = Project.new(:organization_id => organization_id)
    else
      raise RuntimeError.new('You cannot create a new project without passing an organization_id parameter.')
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    @radials = @project.radials
    @questions = @project.questions
    
    # Set breadcrumbs
    _set_project_breadcrumb
    add_breadcrumb 'Edit', edit_project_path(@project)
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end
  
  # GET /projects/1/radials
  # GET /projects/1/radials.json
  def radials
    @project = Project.find(params[:id])
    @radials = @project.radials
    
    respond_to do |format|
      format.html # radials.html.haml
      format.json { render json: @radials }
    end
  end
  
  # POST /projects/1/answer_questions
  # POST /projects/1/answer_questions.json
  def answer_questions
    @project = Project.find(params[:id])
    @question_responses = []
    params[:question_responses].each do |question_id, response|
      @question_responses << QuestionResponse.create!(:question_id => question_id.to_i, :user => current_user, :response => response.to_i)
    end
    
    respond_to do |format|
      format.html { redirect_to @project, notice: 'Your answers have been saved.  Thanks!' }
      format.json { render json: @question_responses, status: :created, location: @project }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  -if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :slug
    = f.text_field :slug
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.hidden_field :organization_id
  .actions
    = f.submit 'Save'

app/views/projects/edit.html.haml
#edit-template.projects-controller
  = render_breadcrumbs

  #project-details
    .title 
      Project Details
    = render 'form'
    
  #radials
    .title
      Radials
    = render :partial => 'radials/radial_description', :collection => @radials, :as => :radial, :locals => {:editable => true}
    = link_to 'Add Radial', new_radial_path(:project_id => @project.id)
  
  #questions
    .title
      Questions
    = render :partial => 'questions/question', :collection => @questions, :locals => {:editable => true}
    = link_to 'Add Question', new_question_path(:project_id => @project.id)

app/views/projects/index.html.haml
%h1 Listing projects

%table
  %tr
    %th Name
    %th Slug
    %th Organization
    %th
    %th
    %th

  - @projects.each do |project|
    %tr
      %td= project.name
      %td= project.slug
      %td= link_to project.organization.name, project.organization
      %td= link_to 'Show', project
      %td= link_to 'Edit', edit_project_path(project)
      %td= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/radials.html.haml
- if @radials.empty?
  This project has no radials configured.  For more information about radials see 
  = link_to('this help page', radials_help_path) + '.'
- else
  = render :partial => 'radials/radial_description', :collection => @radials, :as => :radial

app/views/projects/show.html.haml
#show-template.projects-controller
  #project-header
    #name
      = @project.name
    #edit-link
      [
      = link_to 'Edit', edit_project_path(@project)
      ]
    #description
      = @project.description

  #radials-and-questions
    - if @radials.any?
      #radials
        #learn-more
          = link_to 'Learn More', radials_project_path(@project)
        #data
          = render :partial => 'radials/radial_score', :collection => @radials, :as => :radial
        #graph
          #radar-chart
          :javascript
            var chart = new RadarChart({labels: #{@radial_score_map.map(&:first).inspect}});
            chart.draw(#{@radial_score_map.map(&:last).inspect});
    
    - if @questions.any?
      #questions
        = form_tag(answer_questions_project_path(@project)) do
          = render :partial => 'questions/ask', :collection => @questions, :as => :question
          = submit_tag 'Done!'
        

  #suggestions
    = render :partial => 'suggestions/new'
    = render @suggestions