config/routes.rb
Esteem::Application.routes.draw do
  resources :suggestion_votes

  resources :radials

  resources :question_responses

  resources :questions

  resources :suggestions

  resources :projects do
    member do
      get 'radials'
      post 'answer_questions'
    end
  end

  resources :organizations
  
  match 'help/radials' => 'help#radials', :as => 'radials_help', :via => :get

  
  devise_for :user

  root :to => 'main#index'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :projects
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])

    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :ok }
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.haml
= form_for @organization do |f|
  -if @organization.errors.any?
    #error_explanation
      %h2= "#{pluralize(@organization.errors.count, "error")} prohibited this organization from being saved:"
      %ul
        - @organization.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :slug
    = f.text_field :slug
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/organizations/edit.html.haml
%h1 Editing organization

= render 'form'

= link_to 'Show', @organization
\|
= link_to 'Back', organizations_path

app/views/organizations/index.html.haml
%h1 Listing organizations

%table
  %tr
    %th Name
    %th Slug
    %th
    %th
    %th

  - @organizations.each do |organization|
    %tr
      %td= organization.name
      %td= organization.slug
      %td= link_to 'Show', organization
      %td= link_to 'Edit', edit_organization_path(organization)
      %td= link_to 'Destroy', organization, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Organization', new_organization_path

app/views/organizations/new.html.haml
%h1 New organization

= render 'form'

= link_to 'Back', organizations_path

app/views/organizations/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @organization.name
%p
  %b Slug:
  = @organization.slug
%p
  %b Description:
  = @organization.description

= link_to 'Edit', edit_organization_path(@organization)
\|
= link_to 'Back', organizations_path

#projects-list
  %h3 Projects
  - @organization.projects.each do |project|
    = link_to project.name, project
  = link_to 'New Project', new_project_path(:organization_id => @organization.id)