config/routes.rb
Esteem::Application.routes.draw do
  resources :suggestion_votes

  resources :radials

  resources :question_responses

  resources :questions

  resources :suggestions

  resources :projects do
    member do
      get 'radials'
      post 'answer_questions'
    end
  end

  resources :organizations
  
  match 'help/radials' => 'help#radials', :as => 'radials_help', :via => :get

  
  devise_for :user

  root :to => 'main#index'

end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  
  has_many :suggestion_votes
  
  def vote_score
    suggestion_votes.inject(0) do |s,v| 
      s += v.vote 
    end
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  # GET /suggestions
  # GET /suggestions.json
  def index
    @suggestions = Suggestion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @suggestions }
    end
  end

  # GET /suggestions/1
  # GET /suggestions/1.json
  def show
    @suggestion = Suggestion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @suggestion }
    end
  end

  # GET /suggestions/new
  # GET /suggestions/new.json
  def new
    @suggestion = Suggestion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @suggestion }
    end
  end

  # GET /suggestions/1/edit
  def edit
    @suggestion = Suggestion.find(params[:id])
  end

  # POST /suggestions
  # POST /suggestions.json
  def create
    @suggestion = Suggestion.new(params[:suggestion])

    respond_to do |format|
      if @suggestion.save
        format.html { redirect_to @suggestion.project, notice: 'Thanks for the suggestion!' }
        format.json { render json: @suggestion, status: :created, location: @suggestion.project }
      else
        format.html { render action: "new" }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /suggestions/1
  # PUT /suggestions/1.json
  def update
    @suggestion = Suggestion.find(params[:id])

    respond_to do |format|
      if @suggestion.update_attributes(params[:suggestion])
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suggestions/1
  # DELETE /suggestions/1.json
  def destroy
    @suggestion = Suggestion.find(params[:id])
    @suggestion.destroy

    respond_to do |format|
      format.html { redirect_to suggestions_url }
      format.json { head :ok }
    end
  end
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/suggestions/_form.html.haml
= form_for @suggestion do |f|
  -if @suggestion.errors.any?
    #error_explanation
      %h2= "#{pluralize(@suggestion.errors.count, "error")} prohibited this suggestion from being saved:"
      %ul
        - @suggestion.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :project_id
  = f.hidden_field :user_id
  .field
    = f.text_field :title
  .field
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/suggestions/_new.html.haml
#new-suggestion-partial.suggestions-controller
  #text
    What's your suggestion?
  = render :partial => 'suggestions/form'

app/views/suggestions/_suggestion.haml
.suggestion-partial.suggestions-controller
  .votes
    .vote-up
      = link_to 'Up', suggestion_votes_path('suggestion_vote[suggestion_id]' => suggestion.id, 'suggestion_vote[user_id]' => current_user.id, 'suggestion_vote[vote]' => 1), :method => :post
    .vote-score
      = suggestion.vote_score
    .vote-down
      = link_to 'Down', suggestion_votes_path('suggestion_vote[suggestion_id]' => suggestion.id, 'suggestion_vote[user_id]' => current_user.id, 'suggestion_vote[vote]' => -1), :method => :post
  .title
    = suggestion.title
  .description
    = suggestion.description

app/views/suggestions/edit.html.haml
%h1 Editing suggestion

= render 'form'

= link_to 'Show', @suggestion
\|
= link_to 'Back', suggestions_path

app/views/suggestions/index.html.haml
%h1 Listing suggestions

%table
  %tr
    %th Title
    %th Description
    %th Project
    %th
    %th
    %th

  - @suggestions.each do |suggestion|
    %tr
      %td= suggestion.title
      %td= suggestion.description
      %td= link_to suggestion.project.name, suggestion.project
      %td= link_to 'Show', suggestion
      %td= link_to 'Edit', edit_suggestion_path(suggestion)
      %td= link_to 'Destroy', suggestion, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Suggestion', new_suggestion_path

app/views/suggestions/new.html.haml
%h1 New suggestion

= render 'form'

= link_to 'Back', suggestions_path

app/views/suggestions/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @suggestion.title
%p
  %b Description:
  = @suggestion.description
%p
  %b Project:
  = link_to @suggestion.project.name, @suggestion.project

= link_to 'Edit', edit_suggestion_path(@suggestion)
\|
= link_to 'Back', suggestions_path